defaults:
  - coordiff.yaml
  - _self_


hist_len: 15  # different hist len
gripper_hist_len: 30

gripper_model_cfg:
  hist_len: ${gripper_hist_len}

gripper_dataset_cfg:
  act_chunk: ${act_trunk}
  hist_len: ${gripper_hist_len}
  rot_type: ${rot_type}
